export const licenseList: LicenseItem[] = [
  {
    id: "0BSD",
    name: "BSD Zero Clause License",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    limitations: ["liability", "warranty"],
    userFields: ["holder", "year"],
    usage: 65.7,
  },
  {
    id: "AFL-3.0",
    name: "Academic Free License v3.0",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice", "stateChanges"],
    limitations: ["liability", "trademarkUse", "warranty"],
    usage: 2,
  },
  {
    id: "AGPL-3.0",
    name: "GNU Affero General Public License v3.0",
    abbreviation: "GNU AGPLv3",
    otherId: ["AGPL-3.0-only"],
    variantId: {
      "AGPL-3.0-or-later": "GNU Affero General Public License v3.0 or later",
    },
    permissions: [
      "commercialUse",
      "modification",
      "distribution",
      "patentUse",
      "privateUse",
    ],
    conditions: [
      "licenseAndCopyrightNotice",
      "stateChanges",
      "discloseSource",
      "networkUseIsDistribution",
      "sameLicense",
    ],
    userFields: ["programIntroduction", "author", "year"],
    usage: 439,
  },
  {
    id: "Apache-2.0",
    name: "Apache License 2.0",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice", "stateChanges"],
    limitations: ["liability", "trademarkUse", "warranty"],
    userFields: ["owner", "year"],
    usage: 4000,
  },
  {
    id: "Artistic-2.0",
    name: "Artistic License 2.0",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice", "stateChanges"],
    limitations: ["liability", "trademarkUse", "warranty"],
    usage: 11.3,
  },
  {
    id: "BlueOak-1.0.0",
    name: "Blue Oak Model License 1.0.0",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice"],
    limitations: ["liability", "warranty"],
    usage: 0.3,
  },
  {
    id: "BSD-2-Clause",
    name: 'BSD 2-Clause "Simplified" License',
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice"],
    limitations: ["liability", "warranty"],
    userFields: ["holder", "year"],
    usage: 163,
  },
  {
    id: "BSD-2-Clause-Patent",
    name: "BSD-2-Clause Plus Patent License",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice"],
    limitations: ["liability", "warranty"],
    userFields: ["holder", "year"],
    usage: 0.1,
  },
  {
    id: "BSD-3-Clause",
    name: 'BSD 3-Clause "New" or "Revised" License',
    abbreviation: "Modified BSD License",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice"],
    limitations: ["liability", "warranty"],
    userFields: ["holder", "year"],
    usage: 494,
  },
  {
    id: "BSD-3-Clause-Clear",
    name: "BSD 3-Clause Clear License",
    abbreviation: "Clear BSD",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice"],
    limitations: ["liability", "patentUse", "warranty"],
    userFields: ["holder", "year"],
    usage: 10.1,
  },
  {
    id: "BSD-4-Clause",
    name: 'BSD 4-Clause "Original" or "Old" License',
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice"],
    limitations: ["liability", "warranty"],
    userFields: ["holder", "project", "year"],
    usage: 1.8,
  },
  {
    id: "BSL-1.0",
    name: "Boost Software License 1.0",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNoticeForSource"],
    limitations: ["liability", "warranty"],
    usage: 48.4,
  },
  {
    id: "CC-BY-4.0",
    name: "Creative Commons Attribution 4.0 International",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice", "stateChanges"],
    limitations: ["liability", "patentUse", "trademarkUse", "warranty"],
    usage: 108,
  },
  {
    id: "CC-BY-SA-4.0",
    name: "Creative Commons Attribution Share Alike 4.0 International",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice", "sameLicense", "stateChanges"],
    limitations: ["liability", "patentUse", "trademarkUse", "warranty"],
    usage: 33,
  },
  {
    id: "CC0-1.0",
    name: "Creative Commons Zero v1.0 Universal",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    limitations: ["liability", "patentUse", "trademarkUse", "warranty"],
    usage: 382,
  },
  {
    id: "CECILL-2.1",
    name: "CeCILL Free Software License Agreement v2.1",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: [
      "discloseSource",
      "licenseAndCopyrightNotice",
      "networkUseIsDistribution",
      "sameLicense",
    ],
    limitations: ["liability", "warranty"],
    usage: 0.3,
  },
  {
    id: "CERN-OHL-P-2.0",
    name: "CERN Open Hardware Licence Version 2 - Permissive",
    abbreviation: "CERN OHL v2 Permissive",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice", "stateChanges"],
    limitations: ["liability", "warranty"],
    usage: 1.1,
  },
  {
    id: "CERN-OHL-S-2.0",
    name: "CERN Open Hardware Licence Version 2 - Strongly Reciprocal",
    abbreviation: "CERN OHL v2 Strongly Reciprocal",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: [
      "discloseSource",
      "licenseAndCopyrightNotice",
      "sameLicense",
      "stateChanges",
    ],
    limitations: ["liability", "warranty"],
    usage: 1.5,
  },
  {
    id: "CERN-OHL-W-2.0",
    name: "CERN Open Hardware Licence Version 2 - Weakly Reciprocal",
    abbreviation: "CERN OHL v2 Weakly Reciprocal",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: [
      "discloseSource",
      "licenseAndCopyrightNotice",
      "sameLicenseLibrary",
      "stateChanges",
    ],
    limitations: ["liability", "warranty"],
    usage: 0.6,
  },
  {
    id: "ECL-2.0",
    name: "Educational Community License v2.0",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice", "stateChanges"],
    limitations: ["liability", "trademarkUse", "warranty"],
    userFields: ["owner", "year"],
    usage: 0.4,
  },
  {
    id: "EPL-1.0",
    name: "Eclipse Public License 1.0",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: ["discloseSource", "licenseAndCopyrightNotice", "sameLicense"],
    limitations: ["liability", "warranty"],
    usage: 38.5,
  },
  {
    id: "EPL-2.0",
    name: "Eclipse Public License 2.0",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: ["discloseSource", "licenseAndCopyrightNotice", "sameLicense"],
    limitations: ["liability", "warranty"],
    usage: 48,
  },
  {
    id: "EUPL-1.1",
    name: "European Union Public License 1.1",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: [
      "discloseSource",
      "licenseAndCopyrightNotice",
      "networkUseIsDistribution",
      "sameLicense",
      "stateChanges",
    ],
    limitations: ["liability", "trademarkUse", "warranty"],
    usage: 0.7,
  },
  {
    id: "EUPL-1.2",
    name: "European Union Public License 1.2",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: [
      "discloseSource",
      "licenseAndCopyrightNotice",
      "networkUseIsDistribution",
      "sameLicense",
      "stateChanges",
    ],
    limitations: ["liability", "trademarkUse", "warranty"],
    usage: 8.1,
  },
  {
    id: "GFDL-1.3",
    name: "GNU Free Documentation License v1.3",
    otherId: ["GFDL-1.3-only"],
    variantId: {
      "GFDL-1.3-or-later": "GNU Free Documentation License v1.3 or later",
    },
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: [
      "discloseSource",
      "licenseAndCopyrightNotice",
      "sameLicense",
      "stateChanges",
    ],
    limitations: ["liability", "warranty"],
    usage: 0.6,
  },
  {
    id: "GPL-2.0",
    name: "GNU General Public License v2.0",
    abbreviation: "GNU GPLv2",
    otherId: ["GPL-2.0-only"],
    variantId: {
      "GPL-2.0-or-later": "GNU General Public License v2.0 or later",
    },
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: [
      "discloseSource",
      "licenseAndCopyrightNotice",
      "sameLicense",
      "stateChanges",
    ],
    limitations: ["liability", "warranty"],
    userFields: ["programIntroduction", "author", "year"],
    usage: 634,
  },
  {
    id: "GPL-3.0",
    name: "GNU General Public License v3.0",
    abbreviation: "GNU GPLv3",
    otherId: ["GPL-3.0-only"],
    variantId: {
      "GPL-3.0-or-later": "GNU General Public License v3.0 or later",
    },
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: [
      "discloseSource",
      "licenseAndCopyrightNotice",
      "sameLicense",
      "stateChanges",
    ],
    limitations: ["liability", "warranty"],
    userFields: ["program", "programIntroduction", "author", "year"],
    usage: 3500,
  },
  {
    id: "ISC",
    name: "ISC License",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice"],
    limitations: ["liability", "warranty"],
    userFields: ["holder", "year"],
    usage: 66.4,
  },
  {
    id: "LGPL-2.1",
    name: "GNU Lesser General Public License v2.1",
    abbreviation: "GNU LGPLv2.1",
    otherId: ["LGPL-2.1-only"],
    variantId: {
      "LGPL-2.1-or-later": "GNU Lesser General Public License v2.1 or later",
    },
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: [
      "discloseSource",
      "licenseAndCopyrightNotice",
      "sameLicenseLibrary",
      "stateChanges",
    ],
    limitations: ["liability", "warranty"],
    userFields: ["libraryIntroduction", "author", "year"],
    usage: 75.6,
  },
  {
    id: "LGPL-3.0",
    name: "GNU Lesser General Public License v3.0",
    abbreviation: "GNU LGPLv3",
    otherId: ["LGPL-3.0-only"],
    variantId: {
      "LGPL-3.0-or-later": "GNU Lesser General Public License v3.0 or later",
    },
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: [
      "discloseSource",
      "licenseAndCopyrightNotice",
      "sameLicenseLibrary",
      "stateChanges",
    ],
    limitations: ["liability", "warranty"],
    usage: 120,
  },
  {
    id: "LPPL-1.3c",
    name: "LaTeX Project Public License v1.3c",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: ["discloseSource", "licenseAndCopyrightNotice", "stateChanges"],
    limitations: ["liability", "warranty"],
    usage: 2.3,
  },
  {
    id: "MIT",
    name: "MIT License",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice"],
    limitations: ["liability", "warranty"],
    userFields: ["holder", "year"],
    usage: 19600,
  },
  {
    id: "MIT-0",
    name: "MIT No Attribution",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    limitations: ["liability", "warranty"],
    userFields: ["holder", "year"],
    usage: 38.7,
  },
  {
    id: "MPL-2.0",
    name: "Mozilla Public License 2.0",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: [
      "discloseSource",
      "licenseAndCopyrightNotice",
      "sameLicenseFile",
    ],
    limitations: ["liability", "trademarkUse", "warranty"],
    usage: 165,
  },
  {
    id: "MS-PL",
    name: "Microsoft Public License",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice"],
    limitations: ["trademarkUse", "warranty"],
    usage: 2.2,
  },
  {
    id: "MS-RL",
    name: "Microsoft Reciprocal License",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: [
      "discloseSource",
      "licenseAndCopyrightNotice",
      "sameLicenseFile",
    ],
    limitations: ["liability", "warranty"],
    usage: 0.1,
  },
  {
    id: "MulanPSL-2.0",
    name: "Mulan Permissive Software License, Version 2",
    abbreviation: "Mulan PSL v2",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice"],
    limitations: ["liability", "trademarkUse", "warranty"],
    userFields: ["software", "holder", "year"],
    usage: 6.2,
  },
  {
    id: "NCSA",
    name: "University of Illinois/NCSA Open Source License",
    abbreviation: "UIUC/NCSA",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice"],
    limitations: ["liability", "warranty"],
    userFields: ["holder", "project", "projectUrl", "year"],
    usage: 0.6,
  },
  {
    id: "ODbL-1.0",
    name: "Open Data Commons Open Database License v1.0",
    abbreviation: "ODbL",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: ["discloseSource", "licenseAndCopyrightNotice", "sameLicense"],
    limitations: ["liability", "patentUse", "trademarkUse", "warranty"],
    usage: 0.5,
  },
  {
    id: "OFL-1.1",
    name: "SIL Open Font License 1.1",
    variantId: {
      "OFL-1.1-RFN": "SIL Open Font License 1.1 with Reserved Font Name",
      "OFL-1.1-no-RFN": "SIL Open Font License 1.1 with no Reserved Font Name",
    },
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice", "sameLicense"],
    limitations: ["liability", "warranty"],
    userFields: ["holder", "email", "year"],
    usage: 11.1,
  },
  {
    id: "OSL-3.0",
    name: "Open Software License 3.0",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: [
      "discloseSource",
      "licenseAndCopyrightNotice",
      "networkUseIsDistribution",
      "sameLicense",
      "stateChanges",
    ],
    limitations: ["liability", "trademarkUse", "warranty"],
    usage: 12.6,
  },
  {
    id: "PostgreSQL",
    name: "PostgreSQL License",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice"],
    limitations: ["liability", "warranty"],
    userFields: ["holder", "year"],
    usage: 0.4,
  },
  {
    id: "UPL-1.0",
    name: "Universal Permissive License v1.0",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "patentUse",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNotice"],
    limitations: ["liability", "warranty"],
    userFields: ["holder", "year"],
    usage: 6,
  },
  {
    id: "Unlicense",
    name: "The Unlicense",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    limitations: ["liability", "warranty"],
    usage: 427,
  },
  {
    id: "Vim",
    name: "Vim License",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: [
      "discloseSource",
      "licenseAndCopyrightNotice",
      "sameLicense",
      "stateChanges",
    ],
    userFields: ["projectName"],
    usage: 0.2,
  },
  {
    id: "WTFPL",
    name: "Do What The F*ck You Want To Public License",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    usage: 39.1,
  },
  {
    id: "Zlib",
    name: "zlib License",
    permissions: [
      "commercialUse",
      "distribution",
      "modification",
      "privateUse",
    ],
    conditions: ["licenseAndCopyrightNoticeForSource", "stateChanges"],
    limitations: ["liability", "warranty"],
    userFields: ["holder", "year"],
    usage: 10,
  },
];
